services:
  pwnboard:
    image: ghcr.io/max-49/pwnboard:latest
    environment:
      - FLASK_DEBUG=false
      - FLASK_PORT=5000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PWNBOARD_URL=https://pwnboard.win
      - CACHE_TIME=-1    # Seconds to cache for. set to -1 to disable
      - HOST_TIMEOUT=5
      - CREDS_TIMEOUT=30
      - DEFAULT_USER=admin
      - DEFAULT_USER_PASSWORD=password
      - LOGIN_PAGE_MESSAGE=Contact an admin to get an account!
      - USERS_DB=/opt/pwnboard/data/users.db
      - LOGS_DB=/opt/pwnboard/data/logs.db
    volumes:
      - ./board.json:/opt/pwnboard/board.json:ro
      - pwnboard-data:/opt/pwnboard/data # users.db and logs.db

  redis:
    image: redis:alpine
    restart: always

  reverse-proxy:
    build: ./reverse-proxy
    restart: always
    ports:
      - "443:443"

volumes:
  pwnboard-data:
