version: '3'
services:
  pwnboard:
    build: .
    ports:
      - "${PWNBOARD_PORT}:5000"
    environment:
      - FLASK_DEBUG=true
      - FLASK_PORT=5000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - "PWNBOARD_URL=${PWNBOARD_URL}:${PWNBOARD_PORT}"
      - "SYSLOG_HOST=${SAWMILL_HOST}"
      - "SYSLOG_PORT=${SAWMILL_PORT}"
      - CACHE_TIME=-1    # Seconds to cache for. set to -1 to disable
    volumes:
      - ./board.json:/opt/pwnboard/board.json:ro

  redis:
    image: redis:alpine
    restart: always

  # superset:
  #   image: apache/superset:latest
  #   ports:
  #     - 8088:8088
  #   environment:
  #     - SUPERSET_PASS=i_love_big_oil
  #     - PWN_BOARD=/app/pythonpath/board.json
  #     - PWNBOARD_URL=https://pwnboard.win
  #     - REDIS_HOST=redis
  #     - REDIS_PORT=6379
  #     - MYSQL_HOST=mysql
  #     - MYSQL_USER=pwnboard
  #     - MYSQL_PASS=example
  #     - MYSQL_DB=pwnboard
