version: '3'
services:
  pwnboard:
    build: .
    ports:
      - "${PWNBOARD_PORT}:5000"
    environment:
      - FLASK_DEBUG=false
      - FLASK_PORT=5000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - "PWNBOARD_URL=${PWNBOARD_URL}:${PWNBOARD_PORT}"
      - "SYSLOG_HOST=${SAWMILL_HOST}"
      - "SYSLOG_PORT=${SAWMILL_PORT}"
      - PWN_THEME=blue
      #- PWN_THEME="green"
      - ALERT_TIMEOUT=2  # Minutes to show an alert for
      - HOST_TIMEOUT=5   # Minutes before a host has 'expired'
      - CACHE_TIME=10    # Seconds to cache for. set to -1 to disable

  redis:
    image: redis:alpine
    restart: always
