version: '3'
services:
  pwnboard:
    build: .
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST="redis"
      - REDIS_PORT="6379"
      - PWNTHEME="blue"
      #- PWNTHEME="green"
      - ALERT_TIMEOUT=2  # Minutes to show an alert for
      - HOST_TIMEOUT=5   # Minutes before a host has 'expired'
      - CACHE_TIME=10    # Seconds to cache for

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always

  nginx:
    image: "nginx:latest"
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${PWD}/config/nginx.conf:/etc/nginx/conf.d/pwnboard.conf:ro
