version: '3'
services:
  pwnboard:
    build: .
    ports:
      - "${PWNBOARD_PORT}:5000"
    environment:
      - FLASK_DEBUG=false
      - FLASK_PORT=5000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - "PWNBOARD_URL=${PWNBOARD_URL}:${PWNBOARD_PORT}"
      - "SYSLOG_HOST=${SAWMILL_HOST}"
      - "SYSLOG_PORT=${SAWMILL_PORT}"
      - CACHE_TIME=-1    # Seconds to cache for. set to -1 to disable
    volumes:
      - ./board.json:/opt/pwnboard/board.json:ro

  redis:
    image: redis:alpine
    restart: always
