{
 "title": "PWNBoard Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Callbacks by Tool Over Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "pwnboard_db",
     "rawSql": "SELECT\n  $__timeGroupAlias(received_at, $__interval),\n  application::text AS metric,\n  count(*) AS \"Callbacks\"\nFROM callback_events\nWHERE\n  $__timeFilter(received_at) AND application IS NOT NULL\nGROUP BY 1, 2\n\nORDER BY 1, 2"
    }
   ]
  },
  {
   "title": "Total Callbacks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "pwnboard_db",
     "rawSql": "SELECT COUNT(*) FROM callback_events LIMIT 50 "
    }
   ]
  },
  {
   "title": "Total Credentials Stored",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "pwnboard_db",
     "rawSql": "SELECT COUNT(*) FROM credentials_by_user LIMIT 50 "
    }
   ]
  },
  {
   "title": "Currently Compromised Hosts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "pwnboard_db",
     "rawSql": "SELECT \n  count(DISTINCT ip) AS \"Active IPs\"\nFROM callback_events\nWHERE \n  received_at >= NOW() - INTERVAL '5 minutes'"
    }
   ]
  },
  {
   "title": "Callbacks by Team Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "dataset": "pwnboard_db",
     "rawSql": "SELECT\n  $__timeGroupAlias(received_at, $__interval),\n  team::text AS metric,\n  count(*) AS \"Callbacks\"\nFROM callback_events\nWHERE\n  $__timeFilter(received_at) AND team IS NOT NULL\nGROUP BY 1, 2\nORDER BY 1, 2"
    }
   ]
  },
  {
   "title": "Password Wordcloud",
   "type": "magnesium-wordcloud-panel",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "dataset": "pwnboard_db",
     "rawSql": "SELECT password AS \"word\", COUNT(*) AS \"count\" FROM credentials_by_user GROUP BY password ORDER BY COUNT(*) LIMIT 100 "
    }
   ]
  },
  {
   "title": "Total Callbacks by Tool",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "pwnboard_db",
     "rawSql": "SELECT\n  application AS metric,\n  count(*) AS value\nFROM callback_events\nWHERE application IS NOT NULL AND application != ''\nGROUP BY 1\nORDER BY 2 DESC"
    }
   ]
  },
  {
   "title": "Total Callbacks Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "dataset": "pwnboard_db",
     "rawSql": "-- 2. Get the grand total count of all callbacks\nSELECT\n  $__timeGroupAlias(received_at, $__interval),\n  'Total'::text AS metric,\n  count(*) AS \"Callbacks\"\nFROM callback_events\nWHERE\n  $__timeFilter(received_at)\nGROUP BY 1"
    }
   ]
  },
  {
   "title": "Recently Received Credentials",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "dataset": "pwnboard_db",
     "rawSql": "SELECT ip, username, password, updated_at\nFROM credentials_by_user \nORDER BY updated_at DESC\nLIMIT 10"
    }
   ]
  }
 ]
}